language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
  matrix:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: X0LLn96bSKQLwwqHJa/+Lyu26iPuyoTH6kc2Rk9rHgAjwhgY+2eFDPfkFtMOzPAVmbniRqv9CcGiprKOC1mHBukWosd/FoCXa394p9zXBYT2ERjdMPLj68L+i3K1jcHl7GpW4by9Y099u+FGvPJSQrvGe6ii2Qsj/MyfmpjuSNjTAOK7+jeSgpqyU4wC4j8GNq+8piWtEtzWw0+3H+Kp07vOXgc37KpGo8PTquPTe5HYO+0cwAAvYXgwAGyO9Tm3sRPn7Tnz7Bdp/N+WOtd2N1FodpiOjgmmDZSUr1y0styrEUuBq8O+9eTtbJygmXK2RwO0FiPSukUDVzMuMEbuUSnE/vnU2vUNDX0NjsHBU/XuNt45PY56rtg7YaTsaUHIYLnsQSGhPq/gD24fVSgqq++GoM1tFJHQYsKy+PNonmMcFtkE9TvFCYxqxH4dQPLPE+5GvoQjucXkUP9NWPoa37d7zlQ67XaURQ2yDAbzThE1JiTyeOnSkGMSPL787RTlc9vDvYsfvOLsUQ7AdUfiHTgYaoIsRCZGz0AtI8izi2dk36uOwMcGhmbphN2ib6MOJAalfiyHYGC5wFHh/MZgFx8mf74YMjlNA+gbn+Ul+mI/LpTuQhoaGSxt3EFXJUJVHbIphCRALeCUMfKBrGSqCsiAHuq9iUzfUFNR92aFnhE=
  app: protected-depths-92986
  on:
    repo: adrianasu/react-trello-testing
